### PR TITLE
Revert "Adding .NET 7 support"

### PR DESCRIPTION
**Pull request by slang25**
Reverts dotnet-outdated/dotnet-outdated#348

### CODE REVIEW

**Comment by solrevdev** [comment]
@slang25  I feel really bad about wasting your time like this mate I thought adding support for .NET 7 would have been a nice quick win!

So, I've just tested the reverted version and this is really odd, I'm still getting the same issue, something funky with my machine somehow or do you also get the same issue?

I did have to re-install the .NET 6 SDK but I still have .NET 7 sat side by side so I don't think that's the issue

```text
▲ seedfolder [master] dotnet --version 
7.0.100

▲ seedfolder [master] dotnet --list-sdks
3.1.419 [/usr/local/share/dotnet/sdk]
6.0.403 [/usr/local/share/dotnet/sdk]
7.0.100 [/usr/local/share/dotnet/sdk]

▲ seedfolder [master] dotnet outdated --version
A .NET Core global tool to list outdated Nuget packages.
4.3.1

▲ seedfolder [master] dotnet-outdated -u:prompt
» solrevdev.seedfolder                                                                      
  [net7.0]
  Colorful.Console                      1.2.15 ->       
  Figgle                                0.4.1  ->       
  McMaster.Extensions.CommandLineUtils  4.0.1  ->       

Errors occurred while analyzing dependencies for some of your projects. Are you sure you can connect to all your configured NuGet servers?

Unable to find DOTNET_HOST_PATH environment variable. If you use credential providers for your NuGet sources you need to have this set to the path to the `dotnet` executable.

Version color legend:
<red>   : Major version update or pre-release version. Possible breaking changes.
<yellow>: Minor version update. Backwards-compatible features added.
<green> : Patch version update. Backwards-compatible bug fixes.

Elapsed: 00:00:03.4009963
▲ seedfolder [master] 

```

One final thing I did try `dotnet-outdated -u:prompt` and `dotnet outdated -u:prompt` to see if the space or hyphen made a difference and it did not.

**Comment by slang25** [comment]
Not at all @solrevdev, I should have checked more thoroughly before pushing it. I've got a debugging session here and am narrowing in on the issue. I'll report back later with what I find 😄

**Comment by solrevdev** [comment]
> Not at all @solrevdev, I should have checked more thoroughly before pushing it. I've got a debugging session here and am narrowing in on the issue. I'll report back later with what I find 😄

Ahh cool thanks. Well, if there is anything I can do to help just shout. 🙏

**Comment by slang25** [comment]
*I*  broke it! It was my previous Dependabot merge that updated `NuGet.Common` to the latest version, it contained binary breaking changes (a public type was renamed) and so it was well and truly broken. This was just the first release following that 🤦

**Comment by solrevdev** [comment]
@slang25 oh man good find! 

Thanks for letting me know. 

If you would like me to resubmit my .NET 7 PR (or can you still use the original reverted one) or if I can help in any other way just shout!

**Comment by slang25** [comment]
I'll re-revert your PR, then follow it up with a fix.

This was me uncovering the culprit:
image

**Comment by solrevdev** [comment]
> I'll re-revert your PR, then follow it up with a fix.
> 
> This was me uncovering the culprit: image

Haha!

**Pull request merged**
