### PR TITLE
dependency drift initial version

### PR DESCRIPTION
**Pull request by ranSprd**
I added a first approach of a dependency drift function. That value can be used as quality metric for CIs

### CODE REVIEW

**Comment by coderpatros** [comment]
Hi @ranSprd, are you able to explain your use case for this?

**Comment by ranSprd** [comment]
> Hi @ranSprd, are you able to explain your use case for this?

Sure ;-). 
We ran a lot of components, some small and some huge. There is not always possible to upgrade all of our dependencies. Maybe the new version introduced breaking changes or there are other reasons. A _dependency drift_ is a short metric to see how big is your lack of dependency and make it comparable. Counting only the number of "upgradable" dependencies has no value, for instance if you have 3 of such dependencies - is that a _good_ or a _bad_ value? From my point of view it depends on the number of all of your dependencies. As summary, the _dependency drift_ helps to understand technical debts of your software. From my perspective - dotnet-outdated - is a good place to host such infos.

My approach here is a very simple ratio of outdated and all dependencies. Furthermore it is not so easy to read it from the output. Maybe it would be better to differentiate between major/minor/patch version if you are using semantic versioning...

**Comment by coderpatros** [comment]
My initial thoughts are I don't think we should start incorporating analysis like this.

I think something like this would be better as a separate tool. Perhaps one that you can feed the JSON output to.

I'm thinking something that you could use like this in your builds:

```
dotnet-outdated --output-stdout ./ | dotnet-dependency-drift
```

Currently the output option only writes to a file. But I would be in support of adding functionality to support output to stdout to support usage like this.

**Comment by ranSprd** [comment]
You mean a tool for output analysis of a analysis tool, some kind of chain? I saw `dotnet-outdated` as a dependency analysis tool which reports everything around. You are right, if `dotnet-outdated` is a tool with strong focus on fixing outdated dependencies and adding additional functionality should bring value for the initial area. 

I'm not sure if it make sense to put that 3 lines in a extra tool with much more glue code around. Furthermore the output file of `dotnet-outdated` needs to extend with some counters. For a good assessment of the situation I haven't enough  insights and trust your expertise.

**Comment by coderpatros** [comment]
I'm not necessarily against adding additional metrics as output.

But for CI use cases I'm thinking it's probably better to output more raw data in a machine readable format.

Maybe something like this as part of the JSON output?

```
stats: {
  totalDependencies: 10,
  outdatedDependencies: 3
}
```

And maybe additional stats on dependencies that have major/minor/patch versions available? (I haven't thought too much about how I would consume this information in a CI setting)

I guess percentage of outdated components is another stat. But it just feels like some assumptions are being made that any outdated component is equal.

A good example would be .NET Core versions. Even though 2.1 is an older version than 2.2 using the latest patch version of 2.1 is a much better place to be in than any of the 2.2 versions.

And for some dependencies being on a previous major version is a really bad place to be. Versus being on a previous patch version for a different dependency.

**Comment by ranSprd** [comment]
I think dotnet-libyear makes a better job.

**Pull request closed without merging**
