### PR TITLE
Fix Null Reference Exception (#365)

### LINKED ISSUE #365: Exception while upgrading current release version with --pre-release Always --version-lock Major
If I want to upgrade my current stable branch with all release nuget package to latest nuget package (pre release), I will get below exception. 

 **dotnet-outdated --upgrade --pre-release Always  --version-lock Major**

Analyzing dependencies...Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'value')
   at System.String.StartsWith(String value, StringComparison comparisonType)
   at NuGet.Versioning.FloatRange.Satisfies(NuGetVersion version)
   at NuGet.Versioning.VersionRange.IsBetter(NuGetVersion current, NuGetVersion considering)
   at NuGet.Versioning.VersionRange.FindBestMatch(IEnumerable`1 versions)
   at DotNetOutdated.Core.Services.NuGetPackageResolutionService.ResolvePackageVersions(String packageName, NuGetVersion referencedVersion, IEnumerable`1 sources, VersionRange currentVersionRange, VersionLock versionLock, PrereleaseReporting prerelease, NuGetFramework targetFrameworkName, String projectFilePath, Boolean isDevelopmentDependency, Int32 olderThanDays, Boolean ignoreFailedSources) in /home/runner/work/dotnet-outdated/dotnet-outdated/src/DotNetOutdated.Core/Services/NuGetPackageResolutionService.cs:line 60
   at DotNetOutdated.Program.AddOutdatedDependencyIfNeeded(Project project, TargetFramework targetFramework, Dependency dependency, ConcurrentBag`1 outdatedDependencies) in /home/runner/work/dotnet-outdated/dotnet-outdated/src/DotNetOutdated/Program.cs:line 483
   at DotNetOutdated.Program.AddOutdatedFrameworkIfNeeded(TargetFramework targetFramework, Project project, ConcurrentBag`1 outdatedFrameworks, IConsole console) in /home/runner/work/dotnet-outdated/dotnet-outdated/src/DotNetOutdated/Program.cs:line 470
   at DotNetOutdated.Program.AddOutdatedProjectsIfNeeded(Project project, ConcurrentBag`1 outdatedProjects, IConsole console) in /home/runner/work/dotnet-outdated/dotnet-outdated/src/DotNetOutdated/Program.cs:line 439
   at DotNetOutdated.Program.AnalyzeDependencies(List`1 projects, IConsole console) in /home/runner/work/dotnet-outdated/dotnet-outdated/src/DotNetOutdated/Program.cs:line 407
   at DotNetOutdated.Program.OnExecute(CommandLineApplication app, IConsole console) in /home/runner/work/dotnet-outdated/dotnet-outdated/src/DotNetOutdated/Program.cs:line 187
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at DotNetOutdated.Program.Main(String[] args) in /home/runner/work/dotnet-outdated/dotnet-outdated/src/DotNetOutdated/Program.cs:line 129
[1]    39660 abort      dotnet-outdated --upgrade --pre-release Always --include "ecs." --include

### PR DESCRIPTION
**Pull request by yenneferofvengerberg**
This PR fixes #365

### CODE REVIEW

**Comment by Banner-Keith** [comment]
I was running into this problem as well. I cloned @yenneferofvengerberg's repo and packed and installed it locally and it did fix this issue.

**Comment by Banner-Keith** [comment]
@slang25 Would you have time to review this PR?

**Review by slang25 — APPROVED** [review]
Thank you again for this fix!

**Comment by slang25** [comment]
Thanks for the fix, I was slightly hesitant with upgrading the NuGet packages as I introduced an issue last year by upgrading to 6.3.1 and things broke so I need to revert it (and tests missed it which was a worry), I suspect that could had been down to a mix of package versions, which this PR shouldn't have.

**Pull request merged**
